### ISSUE TITLE
run-tests.sh failing

### ISSUE THREAD

**Issue by jaygrieves** [s2shape/OracleSupplyCollector#1]
Please make the following changes to the run-tests.sh script:

- Make the script executable by default (i.e. chmod +x before committing)
- Remove `sudo` from commands
- Use an Oracle Docker image which can be pulled anonymously

I'm seeing the following error and am unable to run the tests:
`docker: Error response from daemon: Get https://container-registry-phx.oracle.com/v2/database/standard/manifests/12.1.0.2: unauthorized: authentication required`

**Comment by burilovmv** [comment]
Unfortunately, there are no anonymous oracle docker images, user must accept license agreement and login before pulling image

**Comment by jaygrieves** [comment]
@burilovmv Understood about the Oracle Docker container - please add the instructions on how to access it to the README so that anyone testing can get properly set up before running the tests.

**Comment by burilovmv** [comment]
Done. Changed used docker image, which has to be built locally prior to testing
